# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-18 12:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gadgets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gadgetdata',
            name='gadget',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gadgets.Gadget'),
            preserve_default=False,
        ),
    ]
