# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-18 12:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gadgets', '0002_gadgetdata_gadget'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gadgetdata',
            old_name='updated_by',
            new_name='added_by',
        ),
    ]
