# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-18 12:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gadgets', '0003_auto_20160618_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='gadgetdata',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 18, 12, 50, 31, 810976, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
