# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-26 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gadgets', '0007_auto_20160812_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gadgetdata',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
