# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-05 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gadgets', '0008_auto_20160926_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gadgetdata',
            name='timestamp',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
